update element: icon & placeholder
weweb-assets/ww-date pull request #1
Opened 2022-03-15 09:18 UTC by kevinbarfleur

2022-03-15 10:05 UTC, AurelieV requested changes

2022-03-15 10:05 UTC, AurelieV commented on src/wwElement.vue
> +            <wwEditorIcon small name="fontawesome/solid/calendar-day" />
il y a une clef dans la config pour _a maintenant

2022-03-15 10:21 UTC, kevinbarfleur commented on src/wwElement.vue
> +            <wwEditorIcon small name="fontawesome/solid/calendar-day" />
Ah oui, effectivement

2022-03-16 16:08 UTC, AurelieV approved these changes

2022-03-17 09:15 UTC, Kramerbaf approved these changes

2022-03-17 09:15 UTC, merged